# .streamlit/secrets.toml
[google]
api_key = "AIzaSyBoQsCnxICf0keun64246GM0p2dwIR-X3I"  # Replace with your real key

[amadeus]
client_id = "rYe3cDE2YSrD4OlmhOMYnMkH1W05QMbx"
client_secret = "d8SLxyrj84aAIzOo"

[openweather]
api_key = "bd2f3dc7ee16f1ce9b23941cd7131313"

[unsplash]
access_key = "7_EKtKVpcR4ObamVZ2rlihklzXBPHBPjqNbPQl06qMI"

[rapidapi]
key = "56531449a5msha6825acbcb0c4d7p183678jsn99ace807947d"

[exchangerate-api]
key = "f98260fb95e219fcdf1f6bea"

[OPENTRIPMAP]
key = "56531449a5msha6825acbcb0c4d7p183678jsn99ace807947d" 